### ISSUE TITLE
isapprox with keyword arguments

### ISSUE THREAD

**Issue by andyferris** [SimonDanisch/FixedSizeArrays.jl#100]
The definition of `isapprox` doesn't pass along any keyword arguments (being `rtol` and `atol`) which is making it harder for me to do some tests.

**Comment by c42f** [comment]
A thought - most of these problems with missing methods are due to the lack of `FixedArray <: AbstractArray`.  We can't do anything about that right now due to issues in Base, but we can make our lives easier.  What about a simple wrapper as follows:

``` julia
immutable FixedAsAbstractArray{FixedArray{T,NDim,SIZE}} <: AbstractArray{T,NDim}
    A::FSA
end

# define the very few methods required for AbstractArray


# Then, the extended isapprox is simple:
Base.isapprox{FSA<:FixedArray}(a::FSA, b::FSA; kwargs...) = isapprox(FixedAsAbstractArray(a), FixedAsAbstractArray(b); kwargs...)
```

The same goes for a lot of things, and we could automate a lot of the irritation of reimplementing the base AbstractArray functionality each time someone notices that something is missing.

**Comment by andyferris** [comment]
A nice idea, but the simple thing was the `kwargs...` in `isapprox(a,b; kwargs...)` was forgotten about in the definition [here](https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/06ea4bf249ba74a53390510663bcb8e0bcbaff8e/src/array_of_fixedsize.jl#L15). 

With the suggested approach, one would still be apt to forget the keyword arguments, especially if you've never had to use them before. 

For now, I suggest we merge the following code, which copies AbstractArray's version:

``` julia
function isapprox{FSA <: FixedArray, A <: Union{Array, FixedArray}}(x::FSA, y::A; rtol::Real=Base.rtoldefault(eltype(x),eltype(y)), atol::Real=0, norm::Function=vecnorm)
    # Same behaviour as AbstractArray: julia/base/linalg/generic.jl
    d = norm(x - y)
    return isfinite(d) ? d <= atol + rtol*max(norm(x), norm(y)) : x == y
end
```

This gets around my need for keyword arguments anyway (I tried using `atol` to get around `@fsa [1. 0. ; 0. 1.] ≈ @fsa [1. 1e-14; 0. 1.] == false` because FixedSizeArray's version compares elementwise and not via norms),

**Comment by andyferris** [comment]
See PR #103

**Comment by c42f** [comment]
@andyferris as the original author of this issue you should be able to close it off now that the fix is merged.

**Comment by andyferris** [comment]
Thanks all!
