### ISSUE TITLE
WARNING: x.(i) is deprecated; use getfield(x, i) instead.

### ISSUE THREAD

**Issue by dpsanders** [SimonDanisch/FixedSizeArrays.jl#112]
On [the latest Travis build](https://travis-ci.org/SimonDanisch/FixedSizeArrays.jl/jobs/130378115) can be seen that due to recent changes on master, the use of the `x.(i)` is causing a lot of deprecation warnings.

I tried to fix this by just using a regex search, but that results in a recursive calling of `getindex`.

**Comment by SimonDanisch** [comment]
I just merged https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/111 ;)

**Comment by dpsanders** [comment]
Ha, thanks!
