### ISSUE TITLE
Inexact error for Vec(1,0)/2

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/FixedSizeArrays.jl#117]
julia> Vec(1,0)/2
ERROR: InexactError()
 in / at /Users/solver/.julia/v0.4/FixedSizeArrays/src/ops.jl:98

**Comment by c42f** [comment]
This was sorted out when #105 was merged :-) I'm just trying to work out some related changes (see #116) and then I think we can tag a new version.
