### ISSUE TITLE
Tag version 0.2.0

### ISSUE THREAD

**Issue by c42f** [SimonDanisch/FixedSizeArrays.jl#125]
I've been on a bit of a bug fixing and API improvement spree along with @andyferris and @awbsmith for the last few weeks, which has cleaned up a large chunk of problems with fixed array types.

I'm planning to tag version 0.2.0 tomorrow if I get time (version bump since we have breaking API changes here with similar->similar_type).

Let me know if I've forgotten anything and should hold off for a bit!

**Comment by mschauer** [comment]
Go from me: tests in https://github.com/mschauer/Bridge.jl pass (which is quite a big dependency on FixedSizeArrays.jl)

**Comment by SimonDanisch** [comment]
Let me try this out with GLVisualize ;)

**Comment by SimonDanisch** [comment]
Looks good to me :)

**Comment by c42f** [comment]
Awesome, thanks guys!  See JuliaLang/METADATA.jl#5357
