### ISSUE TITLE
Pattern matching on vector slow

### ISSUE THREAD

**Issue by jw3126** [SimonDanisch/FixedSizeArrays.jl#135]
Code like x,y = Vec(1,2) is currently slow then expected. This is a pitty since that pattern is so handy.

```
using FixedSizeArrays
using BenchmarkTools

function match1(v)
    v1,v2,v3,v4 = v
    v1,v2,v3,v4
end

function match2(v)
    v1,v2,v3,v4 = v._
    v1,v2,v3,v4
end
v = rand(Vec{4,Float64})
@show @benchmark match1($v)
@show @benchmark match2($v)
```

@benchmark(match1($(Expr(:$, :v)))) = BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     998
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     15.00 ns (0.00% GC)
  median time:      15.00 ns (0.00% GC)
  mean time:        15.44 ns (0.00% GC)
  maximum time:     98.00 ns (0.00% GC)
@benchmark(match2($(Expr(:$, :v)))) = BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     4.00 ns (0.00% GC)
  median time:      4.00 ns (0.00% GC)
  mean time:        4.09 ns (0.00% GC)
  maximum time:     89.00 ns (0.00% GC)

```
Julia Version 0.4.6-pre+18
Commit 198644a (2016-04-01 03:37 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by jw3126** [comment]
Some Investigations: a,b,c,d = v gets desugared into an iteration. If I change the [next method](https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/c028fba28474e3024aa58727af5a3d91c8638187/src/core.jl) into 

```
next(A::FixedArray, state::Integer) = (A[state], state+1)
```

I get some speedup

```
BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     6.00 ns (0.00% GC)
  median time:      6.00 ns (0.00% GC)
  mean time:        6.11 ns (0.00% GC)
  maximum time:     76.00 ns (0.00% GC)
```

**Comment by SimonDanisch** [comment]
Thanks a lot for catching this :)  I'll investigate!

**Comment by SimonDanisch** [comment]
see: https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/136

**Comment by jw3126** [comment]
Cool!
