### ISSUE TITLE
0.5 splat broken

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/FixedSizeArrays.jl#138]
``` julia
julia> x=Vec(0.,0.);(x...)
ERROR: MethodError: no method matching *(::Type{Any})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
  *(::Complex{Bool}, ::Bool)
  *(::Complex{Bool}, ::Real)
  ...
 in append_any(::FixedSizeArrays.Vec{2,Float64}, ::Vararg{FixedSizeArrays.Vec{2,Float64},N}) at ./essentials.jl:98
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by SimonDanisch** [comment]
Newest master seems to be broken in some way -.- Same problem in #137.
This all breaking thing happens:

``` Julia
julia> supertype(Vec{3, Int})
FixedSizeArrays.FixedArray{Int64,1,Tuple{Any}} 
```

I tried fixing it by using `Tuple{Ref{3}}` but run into some more weird behaviour.

**Comment by SimonDanisch** [comment]
JuliaLang/julia#17247

**Comment by andyferris** [comment]
> I tried fixing it by using Tuple{Ref{3}} but run into some more weird behaviour.

Do you mean `Tuple{Val{3}}`? `Ref{3}` would still not be constructable.

**Comment by c42f** [comment]
Should be addressed in #144

**Comment by dpsanders** [comment]
This now seems to be working with latest Julia v0.5-pre master.

**Comment by SimonDanisch** [comment]
Ah yeah, forgot to close! thanks :)
