### ISSUE TITLE
Should Point - Point be a Vec? 

### ISSUE THREAD

**Issue by cortner** [SimonDanisch/FixedSizeArrays.jl#143]
```
a = Point{3,Float64}((1,2,3))
a - a
# OUTPUT: Point(0.0,0.0,0.0)  
```

But logically, shouldn't the difference between two points be vector? (at least this is what I remember from basic euclidean geometry)

**Comment by SimonDanisch** [comment]
Duplicate of: https://github.com/SimonDanisch/FixedSizeArrays.jl/issues/102

**Comment by cortner** [comment]
sorry - totally missed that.
