### ISSUE TITLE
Implement matrix exponential function (`expm`) for squared `FixedMatrix`s

### ISSUE THREAD

**Issue by cdsousa** [SimonDanisch/FixedSizeArrays.jl#15]

**Comment by SimonDanisch** [comment]
I guess we need these first:

``` Julia
eigfact,
ishermitian,
norm,
gebal # balancing the matrix
gesv # Computes the solution to the system of linear equations with a square coefficient matrix A and multiple right-hand sides.
rcswap # Swap rows i and j and columns i and j in X
```

I feel like we should just wait to get mutable fixedsizearrays and then inherit from AbstractArray and just use whats in base already.

**Comment by cdsousa** [comment]
Hum... Maybe the title can be edited to reflect that.

**Comment by SimonDanisch** [comment]
The problem is, that this might only happen in 1/2 - 1 year, considering how little time the core team has for this. I actually also dont have much time for demands outside my graphic needs.
I will do anything to get to use the `AbstractArray` interface from Base and mutable FSA's, but realistically `FixedSizeArrays` is feature complete for me right now, so I will mostly invest time into `GLVisualize` for now.

So if you have time for this, it might make sense to tackle this immediately.

**Comment by mschauer** [comment]
I could add the 1x1 to 3x3 closed form solutions.

**Comment by SimonDanisch** [comment]
That would be terrific =)

**Comment by mschauer** [comment]
For 3x3 we would need the cubic root jiahao/GSL.jl, so for now postponed. But ...

**Comment by cdsousa** [comment]
I have no clue, but is there a closed form for 4x4?   (I'll use that for se(3) to SE(3) mapping)

In the mean time I've createad a default expm falling back to the Matrix type one: https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/22

**Comment by mschauer** [comment]
just to give you an idea 
this is the 3x3 case in c: https://gist.github.com/mschauer/563fce91872733113796

**Comment by cdsousa** [comment]
:open_mouth:

**Comment by mschauer** [comment]
i translated the expm3 code above to julia, as soon as a `eigvals(Mat{3, 3, T<:Real})` falls from heaven i'll  add `expm{T<:Real}(A::Mat{3, 3, T})`

**Comment by SimonDanisch** [comment]
we could translate this code:
http://barnesc.blogspot.de/2007/02/eigenvectors-of-3x3-symmetric-matrix.html

**Comment by mschauer** [comment]
For 3x3 symmetric matrices https://en.wikipedia.org/wiki/Eigenvalue_algorithm#3.C3.973_matrices could work just fine.

**Comment by SimonDanisch** [comment]
yeeah...that looks simpler :D

**Comment by mschauer** [comment]
This can be closed for now, for 4x4 the wrapper is likely as performant as a possible native FSA solution.

**Comment by SimonDanisch** [comment]
great! Thanks for helping out with this!
