### ISSUE TITLE
expm

### ISSUE THREAD

**Issue by awbsmith** [SimonDanisch/FixedSizeArrays.jl#153]
On the master branch I get the following for expm on a 2x2 matrix:

```
using FixedSizeArrays

A = [0.  1.; 0.   0.] # a constant velocity system model

# as a matrix
expm(A)
2x2 Array{Float64,2}:
 1.0  1.0
 0.0  1.0

# as a fixed size array
expm(Mat(A))
FixedSizeArrays.Mat{2,2,Float64}(
    NaN NaN
    NaN NaN
)
```

**Comment by SimonDanisch** [comment]
Well, the algorithm is different from the one in base.
@mschauer, any idea?
@awbsmith if you know a thing or two about expm (I don't :D ), maybe you can see what goes wrong:
https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/56009694c2827c0fc5130fe0150e0dcdcc2ee2fd/src/expm.jl#L209

**Comment by awbsmith** [comment]
I did a quick google search and found a paper called "Nineteen Dubious Ways to Compute the Exponential of a Matrix", but no papers titled "The Quick and Easy Way to Compute the Exponential of a Matrix".  So I'm out :D.

**Comment by andyferris** [comment]
lol

**Comment by mschauer** [comment]
Haha, that's about the situation. I'll look into it.

**Comment by cortner** [comment]
Nineteen Dubious Ways to Compute the Exponential of a Matrix is actually a fairly popular and well researched article on matrix exponentials. As far as I know, for "small" matrices "scaling and squaring" is still the most widely used method while for large (sparse etc) matrices arising in PDEs, contour integral representations tend to be more performant.

**Comment by mschauer** [comment]
Works on StaticArrays
