### ISSUE TITLE
Missing syntax for (literal) construction of fixed size arrays (as there is for Arrays)

### ISSUE THREAD

**Issue by cdsousa** [SimonDanisch/FixedSizeArrays.jl#16]
Some experiments with a macro here: https://gist.github.com/cdsousa/9ae0e0b7c810a625d45e

It would be great if `[| a, b, c |]` could be used for that. (@SimonDanisch, can you please link relevant Julia issues, I couldn't find them)

**Comment by SimonDanisch** [comment]
you mean this one: JuliaLang/julia#7128 ?
