### ISSUE TITLE
0.6?

### ISSUE THREAD

**Issue by bjarthur** [SimonDanisch/FixedSizeArrays.jl#171]
are there plans to update FixedSizeArrays to julia 0.6?  or do you suggest other packages just switch to StaticArrays (which has dropped support for 0.5)?

**Comment by SimonDanisch** [comment]
The latter... I've actually finished porting to StaticArrays... Problem is, 0.6 is still a little tricky, so 0.6 only is a bit harsh right now -.- 
See:
https://github.com/JuliaGL/GLVisualize.jl/pull/161

**Comment by bjarthur** [comment]
should probably update the README to say that not only does it not work for 0.3 (already there right at the top), but to also say that there are no plans to update it to work with 0.6 and that users should switch to StaticArrays.jl instead.

**Comment by SimonDanisch** [comment]
Thanks for the reminder! I included a remark in the README
