### ISSUE TITLE
Vec in Vec messed up

### ISSUE THREAD

**Issue by kungfooman** [SimonDanisch/FixedSizeArrays.jl#173]
Hey all, I'm trying to use this to generate structs which map nicely to C structs, which works great so far. But when I have a type which has already has a Vec type in it, it messes something up:

	type Person
	  name::Vec{128, Cchar}
	end

	sizeof(Person) # 128 bytes

	type People
	  a::Person
	  b::Person
	end

	sizeof(People) # 16 bytes, basically just 2 references? should be 256 bytes

Anybody knows how to fix that?

**Comment by andyferris** [comment]
Using `immutable` is necessary for that. `type` will always be dealt with as a reference.

**Comment by kungfooman** [comment]
Heh, I just figured `immutable` out, but was asking for an explanation, which you just gave with your answer aswell. Thanks! :)

**Comment by andyferris** [comment]
Also, if you're starting anew, you might equally like to check out StaticArrays.

(@SimonDanisch will this package work on v0.6?)

**Comment by kungfooman** [comment]
Yea, just starting using FixedSizeArrays some hours ago. It just generated many deprecated warnings:

	julia> using FixedSizeArrays
	INFO: Recompiling stale cache file C:\Users\kung\.julia\lib\v0.6\FixedSizeArrays.ji for module FixedSizeArrays.

	WARNING: deprecated syntax "abstract Functor{N}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\FixedSizeArrays.jl:23.
	Use "abstract type Functor{N} end" instead.

	WARNING: deprecated syntax "abstract FixedArray{T,NDim,SIZE}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:2.
	Use "abstract type FixedArray{T,NDim,SIZE} end" instead.

	WARNING: deprecated syntax "abstract MutableFixedArray{T,NDim,SIZE}<:FixedArray{T,NDim,SIZE}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:3.
	Use "abstract type MutableFixedArray{T,NDim,SIZE}<:FixedArray{T,NDim,SIZE} end" instead.

	WARNING: deprecated syntax "typealias MutableFixedVector{T,CARDINALITY} MutableFixedArray{T,1,Tuple{CARDINALITY}}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:5.
	Use "MutableFixedVector{T,CARDINALITY} = MutableFixedArray{T,1,Tuple{CARDINALITY}}" instead.

	WARNING: deprecated syntax "typealias MutableFixedMatrix{T,M,N} MutableFixedArray{T,2,Tuple{M,N}}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:6.
	Use "MutableFixedMatrix{T,M,N} = MutableFixedArray{T,2,Tuple{M,N}}" instead.

	WARNING: deprecated syntax "typealias FixedVector{CARDINALITY,T} FixedArray{T,1,Tuple{CARDINALITY}}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:8.
	Use "FixedVector{CARDINALITY,T} = FixedArray{T,1,Tuple{CARDINALITY}}" instead.

	WARNING: deprecated syntax "typealias FixedMatrix{Row,Column,T} FixedArray{T,2,Tuple{Row,Column}}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:9.
	Use "FixedMatrix{Row,Column,T} = FixedArray{T,2,Tuple{Row,Column}}" instead.

	WARNING: deprecated syntax "abstract FixedVectorNoTuple{CARDINALITY,T}<:FixedVector{CARDINALITY,T}" at C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\core.jl:11.
	Use "abstract type FixedVectorNoTuple{CARDINALITY,T}<:FixedVector{CARDINALITY,T} end" instead.
	WARNING: Base.linearindexing is deprecated, use Base.IndexStyle instead.
	  likely near C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\destructure.jl:13
	WARNING: Base.linearindexing is deprecated, use Base.IndexStyle instead.
	  likely near C:\Users\kung\.julia\v0.6\FixedSizeArrays\src\destructure.jl:13

	WARNING: deprecated syntax "function .+(...)".
	Use "function Base.broadcast(::typeof(+), ...)" instead.

	WARNING: deprecated syntax "function .+(...)".
	Use "function Base.broadcast(::typeof(+), ...)" instead.

	WARNING: deprecated syntax "function .+(...)".
	Use "function Base.broadcast(::typeof(+), ...)" instead.

	WARNING: deprecated syntax "function .+(...)".
	Use "function Base.broadcast(::typeof(+), ...)" instead.

	WARNING: deprecated syntax "function .+(...)".
	Use "function Base.broadcast(::typeof(+), ...)" instead.

	WARNING: deprecated syntax "function .-(...)".
	Use "function Base.broadcast(::typeof(-), ...)" instead.

	WARNING: deprecated syntax "function .-(...)".
	Use "function Base.broadcast(::typeof(-), ...)" instead.

	WARNING: deprecated syntax "function .-(...)".
	Use "function Base.broadcast(::typeof(-), ...)" instead.

	WARNING: deprecated syntax "function .-(...)".
	Use "function Base.broadcast(::typeof(-), ...)" instead.

	WARNING: deprecated syntax "function .-(...)".
	Use "function Base.broadcast(::typeof(-), ...)" instead.

	WARNING: deprecated syntax "function .*(...)".
	Use "function Base.broadcast(::typeof(*), ...)" instead.

	WARNING: deprecated syntax "function .*(...)".
	Use "function Base.broadcast(::typeof(*), ...)" instead.

	WARNING: deprecated syntax "function .*(...)".
	Use "function Base.broadcast(::typeof(*), ...)" instead.

	WARNING: deprecated syntax "function .*(...)".
	Use "function Base.broadcast(::typeof(*), ...)" instead.

	WARNING: deprecated syntax "function .*(...)".
	Use "function Base.broadcast(::typeof(*), ...)" instead.

	WARNING: deprecated syntax "function ./(...)".
	Use "function Base.broadcast(::typeof(/), ...)" instead.

	WARNING: deprecated syntax "function ./(...)".
	Use "function Base.broadcast(::typeof(/), ...)" instead.

	WARNING: deprecated syntax "function ./(...)".
	Use "function Base.broadcast(::typeof(/), ...)" instead.

	WARNING: deprecated syntax "function ./(...)".
	Use "function Base.broadcast(::typeof(/), ...)" instead.

	WARNING: deprecated syntax "function ./(...)".
	Use "function Base.broadcast(::typeof(/), ...)" instead.

	WARNING: deprecated syntax "function .\(...)".
	Use "function Base.broadcast(::typeof(\), ...)" instead.

	WARNING: deprecated syntax "function .\(...)".
	Use "function Base.broadcast(::typeof(\), ...)" instead.

	WARNING: deprecated syntax "function .\(...)".
	Use "function Base.broadcast(::typeof(\), ...)" instead.

	WARNING: deprecated syntax "function .\(...)".
	Use "function Base.broadcast(::typeof(\), ...)" instead.

	WARNING: deprecated syntax "function .\(...)".
	Use "function Base.broadcast(::typeof(\), ...)" instead.

	WARNING: deprecated syntax "function .^(...)".
	Use "function Base.broadcast(::typeof(^), ...)" instead.

	WARNING: deprecated syntax "function .^(...)".
	Use "function Base.broadcast(::typeof(^), ...)" instead.

	WARNING: deprecated syntax "function .^(...)".
	Use "function Base.broadcast(::typeof(^), ...)" instead.

	WARNING: deprecated syntax "function .^(...)".
	Use "function Base.broadcast(::typeof(^), ...)" instead.

	WARNING: deprecated syntax "function .^(...)".
	Use "function Base.broadcast(::typeof(^), ...)" instead.

	WARNING: deprecated syntax "function .==(...)".
	Use "function Base.broadcast(::typeof(==), ...)" instead.

	WARNING: deprecated syntax "function .==(...)".
	Use "function Base.broadcast(::typeof(==), ...)" instead.

	WARNING: deprecated syntax "function .==(...)".
	Use "function Base.broadcast(::typeof(==), ...)" instead.

	WARNING: deprecated syntax "function .==(...)".
	Use "function Base.broadcast(::typeof(==), ...)" instead.

	WARNING: deprecated syntax "function .==(...)".
	Use "function Base.broadcast(::typeof(==), ...)" instead.

	WARNING: deprecated syntax "function .!=(...)".
	Use "function Base.broadcast(::typeof(!=), ...)" instead.

	WARNING: deprecated syntax "function .!=(...)".
	Use "function Base.broadcast(::typeof(!=), ...)" instead.

	WARNING: deprecated syntax "function .!=(...)".
	Use "function Base.broadcast(::typeof(!=), ...)" instead.

	WARNING: deprecated syntax "function .!=(...)".
	Use "function Base.broadcast(::typeof(!=), ...)" instead.

	WARNING: deprecated syntax "function .!=(...)".
	Use "function Base.broadcast(::typeof(!=), ...)" instead.

	WARNING: deprecated syntax "function .<(...)".
	Use "function Base.broadcast(::typeof(<), ...)" instead.

	WARNING: deprecated syntax "function .<(...)".
	Use "function Base.broadcast(::typeof(<), ...)" instead.

	WARNING: deprecated syntax "function .<(...)".
	Use "function Base.broadcast(::typeof(<), ...)" instead.

	WARNING: deprecated syntax "function .<(...)".
	Use "function Base.broadcast(::typeof(<), ...)" instead.

	WARNING: deprecated syntax "function .<(...)".
	Use "function Base.broadcast(::typeof(<), ...)" instead.

	WARNING: deprecated syntax "function .<=(...)".
	Use "function Base.broadcast(::typeof(<=), ...)" instead.

	WARNING: deprecated syntax "function .<=(...)".
	Use "function Base.broadcast(::typeof(<=), ...)" instead.

	WARNING: deprecated syntax "function .<=(...)".
	Use "function Base.broadcast(::typeof(<=), ...)" instead.

	WARNING: deprecated syntax "function .<=(...)".
	Use "function Base.broadcast(::typeof(<=), ...)" instead.

	WARNING: deprecated syntax "function .<=(...)".
	Use "function Base.broadcast(::typeof(<=), ...)" instead.

	WARNING: deprecated syntax "function .>(...)".
	Use "function Base.broadcast(::typeof(>), ...)" instead.

	WARNING: deprecated syntax "function .>(...)".
	Use "function Base.broadcast(::typeof(>), ...)" instead.

	WARNING: deprecated syntax "function .>(...)".
	Use "function Base.broadcast(::typeof(>), ...)" instead.

	WARNING: deprecated syntax "function .>(...)".
	Use "function Base.broadcast(::typeof(>), ...)" instead.

	WARNING: deprecated syntax "function .>(...)".
	Use "function Base.broadcast(::typeof(>), ...)" instead.

	WARNING: deprecated syntax "function .>=(...)".
	Use "function Base.broadcast(::typeof(>=), ...)" instead.

	WARNING: deprecated syntax "function .>=(...)".
	Use "function Base.broadcast(::typeof(>=), ...)" instead.

	WARNING: deprecated syntax "function .>=(...)".
	Use "function Base.broadcast(::typeof(>=), ...)" instead.

	WARNING: deprecated syntax "function .>=(...)".
	Use "function Base.broadcast(::typeof(>=), ...)" instead.

	WARNING: deprecated syntax "function .>=(...)".
	Use "function Base.broadcast(::typeof(>=), ...)" instead.

	WARNING: deprecated syntax "function .+(...)".
	Use "function Base.broadcast(::typeof(+), ...)" instead.

Just downloaded newest 0.6 release:	
	
	julia> versioninfo()
	Julia Version 0.6.0
	Commit 903644385b* (2017-06-19 13:05 UTC)
	Platform Info:
	  OS: Windows (x86_64-w64-mingw32)
	  CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
	  WORD_SIZE: 64
	  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
	  LAPACK: libopenblas64_
	  LIBM: libopenlibm
	  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

**Comment by SimonDanisch** [comment]
Definitely check out StaticArrays instead of FixedSizeArrays ;)
Should offer almost the same functionality, especially if you use the submodule StaticArrays.FixedSizeArrays

**Comment by kungfooman** [comment]
Thanks, I just switched out all `Vec` with `SVector`, works just as great. Probably it is in areas better which I don't quite understand yet. :D
