### ISSUE TITLE
Issues attempting to use

### ISSUE THREAD

**Issue by garrison** [SimonDanisch/FixedSizeArrays.jl#3]
I've been trying to check out what you are doing here with `FixedSizeArrays`.  I realize it's not ready for production use, but wanted to catalog a few issues I ran into.

`test/runtests.jl` requires GeometryTypes, but it is not listed in a `REQUIRE` file.  In fact, `GeometryTypes` depends on `FixedSizeArrays`, so it seems strange to me to have a test require it at all.

Also, there are various other things in the `test/` directory, but none of them are `include`d by `runtests.jl`.

When simply importing `FixedSizeArrays` on the latest `julia` `master`, I get the following error:

```
ERROR: LoadError: LoadError: TypeError: apply_type: in MutableFixedArray, expected Type{T}, got Tuple{TypeVar}
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/garrison/.julia/v0.4/FixedSizeArrays/src/core.jl, in expression starting on line 12
while loading /home/garrison/.julia/v0.4/FixedSizeArrays/src/FixedSizeArrays.jl, in expression starting on line 3
```

**Comment by SimonDanisch** [comment]
Thanks for trying it out Jim!
This package still haven't received a cleaning, so it's still in the chaos that I produced to get it running.
The error is not a surprise, as I haven't fixed it up for the tuples yet.
I'm waiting for this: https://github.com/SimonDanisch/FixedSizeArrays.jl/commit/21a2c2136169a6b4a512488e0e0ed703de59fa35

I need GeometryTypes, as FixedSizeArray is kind of abstract (which will change with the native tuples) in the regard, that it doesn't define any types. I could just define some types in the runtests.
Well things like that will be part of a clean up.
Right now, I'm just making sure that everything works with GLAbstraction, which is my real test case I rely on at the moment.

**Comment by SimonDanisch** [comment]
This should be long fixed...

**Comment by garrison** [comment]
Great! :)  I'll have to check it out again.
