### ISSUE TITLE
Monkey patches

### ISSUE THREAD

**Issue by mschauer** [SimonDanisch/FixedSizeArrays.jl#49]
There are some monkey patches I made to get my stochastic differential equation code running using FixedSizeArrays (and it runs): https://github.com/mschauer/Bridge.jl/blob/master/src/fsa.jl
Not all of those ad hoc definitions are meaningful, but the 2x2 cholesky and code extending UniformScaling s could possibly incorporated here?

**Comment by mschauer** [comment]
See also #37

**Comment by SimonDanisch** [comment]
Sure, bring in the code ;)

**Comment by mschauer** [comment]
Done
