### ISSUE TITLE
equality function with standard arrays is missing

### ISSUE THREAD

**Issue by schlady** [SimonDanisch/FixedSizeArrays.jl#5]
``` julia
julia> FixedSizeArrays.Vec3(1,2,3) == [1,2,3]
false
```

whereas

``` julia
julia> ImmutableArrays.Vector2(1,2) == [1,2]
true
```

**Comment by SimonDanisch** [comment]
Ah yeah...The most elegant solution to fix this is to inherit from AbstractArray... But this gives millions of ambiguity warnings.
Probably its easier to just implement it...
