### ISSUE TITLE
Diagonal, symmetric, triangular

### ISSUE THREAD

**Issue by mschauer** [SimonDanisch/FixedSizeArrays.jl#50]
Matrices with shape would be nice to have of course. Symmetric and Triangular in Base are parametrized by abstract matrices. Could they be inherited from Base in a hypothetical future where a fixed size array is an abstract array? Diagonal is parametrized by element type, so this would have to be implemented directly in any case. Implementing a Diagonal fixed size array would be worthwhile therefore imho.

**Comment by SimonDanisch** [comment]
The long term goal is to be compatible with `AbstractArray` and have function defined which both work for base arrays and `FixedSizeArrays`! At some point I was thinking to also implement `views` and some types like `Diagonal` matrices. Never got to it, so if you have ideas and implementations, go for it!
