### ISSUE TITLE
RowFunctor is still needed for transpose()

### ISSUE THREAD

**Issue by mschauer** [SimonDanisch/FixedSizeArrays.jl#54]
It was by accident removed at 08beac4dba959bfe .

**Comment by SimonDanisch** [comment]
you mean for `transpose`?
That's the only location I can find the rowfunctor.

**Comment by mschauer** [comment]
ah, yes, i was calling row and transpose in the same function and misattributed the error.

**Comment by SimonDanisch** [comment]
Feel free to put it back! I won't be able to so until tomorrow!

**Comment by mschauer** [comment]
Fixed by #55
