### ISSUE TITLE
cross product

### ISSUE THREAD

**Issue by michaellindon** [SimonDanisch/FixedSizeArrays.jl#77]
Hi Guys,

I'm trying to convert my old code, a simpler outer product of `A[:,1]*A[1,:]` (A is symmetric).

When A is a Mat, A[1:end,1] returns a tuple. Im wrapping this with Vec(A[1:end,1]) to get a vector again, but cross doesn't give me what I'd expect:

```
julia> A
FixedSizeArrays.Mat{3,3,Float64}(
    1.8954132091466565 1.6825020352962574 1.6404327518296233
    1.6825020352962574 1.60975356511942 1.607090604907342
    1.6404327518296233 1.607090604907342 1.7543780771178934
)


julia> cross(Vec(A[1,1:d]),Vec(A[1:d,1]))
FixedSizeArrays.Vec{3,Float64}((0.0,0.0,0.0))
```

I've looked at the source code, but I'm afraid I'm quite new to Julia.

**Comment by mschauer** [comment]
In julia, the `cross` is the cross product, "the magnitude of the product equals the area of a parallelogram with the vectors for sides". Your matrix is symmetric, therefore this returns a 0-vector. You mean the outer product `Vec(A[1:d,1])*Vec(A[1,1:d])'`
