### ISSUE TITLE
FixedMatrix(1.0) causes Julia to hang

### ISSUE THREAD

**Issue by KristofferC** [SimonDanisch/FixedSizeArrays.jl#80]
It looks like it is doing some recursion in `constructors.jl`.

I know you are not supposed to do this but I accidentally did anyway :P

**Comment by SimonDanisch** [comment]
On what version are you? I get an error instead (on master).
By the way, `FixedMatrix` is abstract, so you should rather use `Mat(1.0)`, which seems to work fine.

**Comment by KristofferC** [comment]
Crap, I had accidentally dirtied the repo so I didn't have the newest version. Works fine on master, sorry for the noise.

**Comment by SimonDanisch** [comment]
No worries :)
