### ISSUE TITLE
real has no method match real(::Point)

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/FixedSizeArrays.jl#82]
This gives an unexpected error:

``` julia
real(Point((1,2)))
```

**Comment by c42f** [comment]
Personally I don't think `Point` is so analogous to `Complex` that it makes sense to define `real` or `imag`.  I assume this is where you're coming from given the discussion in #83?

One way to think about the distinction is that subtypes of `FixedArray` are members of a vector space (though admittedly with more operations besides), whereas objects of type `Complex` are a scalar in a field.  Vector spaces and fields are rather different algebraic structures.

**Comment by SimonDanisch** [comment]
Oh, totally overlooked this issue, sorry.... I agree with @c42f, but I must admit that my math knowledge is very limited!

**Comment by dlfivefifty** [comment]
Oh, this issue I was expecting the vectorised definition:

real(Point(1+im,2+2im)) == Point(1,2)

**Comment by SimonDanisch** [comment]
ah, that seems reasonable... Should only be as much as adding `:real` to the unary ops list... Can do when I'm home!

**Comment by SimonDanisch** [comment]
Oh, not if you need `real(Point(1+im,2+2im)) == Point(1,2)`....Ops still don't allow to change the element type :(

**Comment by c42f** [comment]
Right, that seems quite reasonable.  See also #63 for discussion about return types

**Comment by c42f** [comment]
Fixed via #105
