### ISSUE TITLE
Support Point(1,2)*[1,2,3]?

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/FixedSizeArrays.jl#83]
I'm looking for a data type for representing points in 2D/3D that works like Complex, apart from multiplication, and Point seems like the right thing.  But for me it'd be convenient if

``` julia
p=Point(1,2)
p*[1,2,3]  == [1*p,2*p,3*p]
```

Is this sensible standard behaviour that I should make a pull request for?  Or am I better off creating my own Point-like data type:

``` julia
type MyPoint{N,T} <: FixedVector{N,T}
  _::NTuple{N,T}
end

*(p::MyPoint,v::Vector)=map(x->x*p,v)
```

**Comment by SimonDanisch** [comment]
Hm, I think I'd prefer:

``` Julia
p=Point(1,2,3)
p.*[1,2,3]  == Point(1*p1,2*p2,3*p3)
```

Since the point is stack allocated and it would not be optimal if you actually need a point for the next operations.
Is there a reason why you need to mix them?

**Comment by dlfivefifty** [comment]
It's to replicate

(1+2im)*[1,2,3]

Points to me are analogous  to complex numbers, so I'd expect them to act like numbers in this setting.

I would not support this behaviour for Vec, however, only Point

**Comment by SimonDanisch** [comment]
This sounds like you rather want a new type...

> Points to me are analogous  to complex numbers, so I'd expect them to act like numbers in this setting.

I don't have any of these expectations, but then again, I've only used points for graphics.

**Comment by dlfivefifty** [comment]
OK in that case I'll make a new type
