### ISSUE TITLE
main not defined

### ISSUE THREAD

**Issue by blegat** [SimonDanisch/FixedSizeArrays.jl#84]
I have the following error with the latest version (I did Pkg.checkout) of FixedSizeArrays, GeometryTypes and GLVisualize using julia v0.5:

```
julia> using GeometryTypes
julia> using GLVisualize
julia> x = SimpleRectangle(0,0,1,1)
GeometryTypes.SimpleRectangle{Int64}(0,0,1,1)
julia> y = visualize(x)
ERROR: UndefVarError: main not defined
 [inlined code] from /home/blegat/.julia/v0.5/FixedSizeArrays/src/mapreduce.jl:65
 in default at /home/blegat/.julia/v0.5/GLVisualize/src/visualize_interface.jl:2
 in visualize at /home/blegat/.julia/v0.5/GLVisualize/src/visualize_interface.jl:18
 in eval at ./boot.jl:263
```

**Comment by SimonDanisch** [comment]
whoops... Untested code... should be fixed in: https://github.com/JuliaGL/GLVisualize.jl/commit/cc0860a22ec0609d4ae071428d21c885cbfd47ce
Note that your Rectangle is only 1 pixel x 1 pixel... and you haven't created a screen, which is mandatory for calling visualize.

**Comment by blegat** [comment]
Yes I know, I just made the steps to reproduce the bug minimal :)

**Comment by SimonDanisch** [comment]
Good :)

**Comment by blegat** [comment]
Works perfect now, thanks !
