### ISSUE TITLE
isapprox minor problem

### ISSUE THREAD

**Issue by jw3126** [SimonDanisch/FixedSizeArrays.jl#86]
Hi,
great package! There is a minor inconvenience with isapprox:

`isapprox(Vec(0., 0, 1), [0., 0, 1])`
works but
`isapprox(Vec(0., 0, 1), Vec(0., 0, 1))`
has no method:

```
LoadError: MethodError: `isapprox` has no method matching isapprox(::FixedSizeArrays.Vec{3,Float64}, ::FixedSizeArrays.Vec{3,Float64})
Closest candidates are:
  isapprox{FSA<:FixedSizeArrays.FixedArray{T,NDim,SIZE}}(::FSA<:FixedSizeArrays.FixedArray{T,NDim,SIZE}, !Matched::Array{T,N})
```

BTW the readme says this package is 0.4 only. Does this mean, that the package is going to be deprecated for 0.5?

**Comment by SimonDanisch** [comment]
> BTW the readme says this package is 0.4 only. Does this mean, that the package is going to be deprecated for 0.5?

No, that's from times where 0.4 wasn't released. I should update the README! ;)

**Comment by jw3126** [comment]
Glad to hear FixedSizeArrays will survive!
