### ISSUE TITLE
Incorrect error message when multiplying matrix by FixedVectorNoTuple

### ISSUE THREAD

**Issue by rdeits** [SimonDanisch/FixedSizeArrays.jl#90]
Multiplying a `Mat` object by a subtype of `FixedVectorNoTuple` fails and produces an odd error message:

``` julia
julia> using FixedSizeArrays

julia> immutable RGB{T} <: FixedVectorNoTuple{3, T}
           r::T
           g::T
           b::T
           function RGB(a::NTuple{3, T}) #needs to be like this to keep constructor code sane
               new{T}(a[1], a[2], a[3])
           end
       end

julia> M = Mat{3, 3, Float64}(0)
FixedSizeArrays.Mat{3,3,Float64}(
    0.0 0.0 0.0
    0.0 0.0 0.0
    0.0 0.0 0.0
)


julia> rgb = RGB{Float64}(0)
RGB{Float64}(0.0,0.0,0.0)

julia> M * rgb
ERROR: DimensionMismatch("3 != 3 in FixedSizeArrays.Mat{3,3,Float64} and RGB{Float64}")
 in * at /Users/rdeits/.julia/v0.4/FixedSizeArrays/src/ops.jl:248
```

Specifically, the `3 != 3` is likely to be a bit confusing :wink: 

It looks like there probably just needs to be another definition of (*) for FixedMatrix and FixedVector?

**Comment by SimonDanisch** [comment]
I think we removed them at some point because it wasn't working for some edge cases, I think.

https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/41
https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/39

> It looks like there probably just needs to be another definition of (*) for FixedMatrix and FixedVector?

That sounds about right! :)

**Comment by rdeits** [comment]
Okay, I'll see if I can add an appropriate definition
