### ISSUE TITLE
Add isapprox(Vec(1.,2.),Vec(3.,4.))

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/FixedSizeArrays.jl#94]
This currently is not implemented but should be:

``` julia
isapprox(Vec(1.,2.),Vec(3.,4.))
```

**Comment by SimonDanisch** [comment]
It is actually implemented on master: https://github.com/SimonDanisch/FixedSizeArrays.jl/commit/ba4161037b574cafcf2eabea9e5082a06bba8963

Best,
Simon
